# Generated by Django 5.0.2 on 2025-11-22 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticket_attendee_email_ticket_attendee_name_and_more'),
        ('stores', '0002_alter_store_name_alter_store_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='stores.store'),
        ),
    ]
