# Generated by Django 5.0.2 on 2025-12-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_organizerinvitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If true, hidden from public listings but accessible via link.'),
        ),
    ]
